---
title: "Benchmarking mlr3fda"
output: html_document
---

```{r}
library(data.table)
library(mlr3fda)
library(mlr3pipelines)

setDTthreads(threads = 1)

generate_data <- function(n_patients = 100, n_weeks = 10, seed = 1234) {
  set.seed(seed)
  lapply(paste0("patient_", seq(1, n_patients)), function(patient_id) {
    tibble::tibble(
      patient_id = as.factor(patient_id),
      week = sample(1:n_weeks, n_weeks, replace = FALSE),
      systolic_bp = rnorm(n_weeks, 120, 15),
      diastolic_bp = rnorm(n_weeks, 80, 10),
      heart_rate = rnorm(n_weeks, 70, 10),
      age = sample(20:90, n_weeks, replace = TRUE),
      gender = as.factor(sample(c("Male", "Female"), n_weeks, replace = TRUE)),
      recovery_rate = systolic_bp * 0.3 + diastolic_bp * 0.4 + heart_rate * 0.2
    )
  }) |>
    dplyr::bind_rows()
}

analyse_dplyr <- function(patients, window_start, window_end) {
  patients |>
    dplyr::filter(between(week, window_start, window_end)) |>
    dplyr::group_by(patient_id, measurement_type) |>
    dplyr::summarise(
      mean = mean(measurement_value),
      var = var(measurement_value),
      slope = coef(lm(measurement_value ~ week))[[2]],
      .groups = "drop"
    )
}

analyse_dt <- function(patients, window_start, window_end) {
  patients <- as.data.table(patients)
  patients[between(week, window_start, window_end), .(
    mean = mean(measurement_value),
    var = var(measurement_value),
    slope = coef(lm(measurement_value ~ week))[[2]]
  ), keyby = .(patient_id, measurement_type)]
}

analyse_fda <- function(task, left = -Inf, right = Inf) {
  po_fmean <- po("ffs",
    feature = "mean",
    id = "mean",
    drop = FALSE,
    left = left,
    right = right
  )
  po_fvar <- po("ffs",
    feature = "var",
    id = "var",
    drop = FALSE,
    left = left,
    right = right
  )
  po_slope <- po("ffs",
    feature = "slope",
    id = "slope",
    drop = FALSE,
    left = left,
    right = right
  )
  graph <- po_fmean %>>%
    po_fvar %>>%
    po_slope
  graph$train(task)
}
```

```{r}
n_weeks <- 52
window_start <- 2
window_end <- floor(n_weeks * 0.8)

patients <- generate_data(n_patients = 100, n_weeks = n_weeks)
patients_long <- patients |>
  tidyr::pivot_longer(
    cols = systolic_bp:heart_rate,
    names_to = "measurement_type",
    values_to = "measurement_value"
  )

patients_tf <- patients |>
  dplyr::select(-c(age, gender, recovery_rate)) |>
  tidyfun::tf_nest(systolic_bp:heart_rate, .id = "patient_id", .arg = "week")
patients_tf$target <- rnorm(nrow(patients_tf), 0, 1)
task <- as_task_regr(patients_tf, target = "target", id = "patients")

benchmark <- microbenchmark::microbenchmark(
  dplyr = analyse_dplyr(patients_long, window_start, window_end),
  data_table = analyse_dt(patients_long, window_start, window_end),
  fda = analyse_fda(task, window_start, window_end),
  times = 100L
)
benchmark
```
